//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EHksperiment1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список услуг.
    /// </summary>
    // *** Start programmer edit section *** (СписокУслуг CustomAttributes)

    // *** End programmer edit section *** (СписокУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("Список услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокУслугE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("СписокУслугL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class СписокУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СписокУслуг CustomMembers)

        // *** End programmer edit section *** (СписокУслуг CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СписокУслуг.Наименование CustomAttributes)

        // *** End programmer edit section *** (СписокУслуг.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СписокУслуг.Наименование Get start)

                // *** End programmer edit section *** (СписокУслуг.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СписокУслуг.Наименование Get end)

                // *** End programmer edit section *** (СписокУслуг.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокУслуг.Наименование Set start)

                // *** End programmer edit section *** (СписокУслуг.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СписокУслуг.Наименование Set end)

                // *** End programmer edit section *** (СписокУслуг.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокУслугE", typeof(IIS.EHksperiment1.СписокУслуг));
                }
            }
            
            /// <summary>
            /// "СписокУслугL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокУслугL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокУслугL", typeof(IIS.EHksperiment1.СписокУслуг));
                }
            }
        }
    }
}
